#title in header
# title: "Page title"
title: "I tinker, therefore I am..."

#main info
#owner
owner: "Bart Karalus"
email: bart.karalus@proton.me
info: "Software engineer & general tinkerer based in Poland."
desc: "This is an imaginary lab where all my ideas and projects get forged into some form of reality."
greeting: "I tinker, therefore I am..."

#menu
menu:
  Projects: /projects
  Recommended: /recommended
  About: /about

#index/main page max show posts (in number)
max_post: 6

# Colors use hex color without #
# Theme color
# tcolor: 0FA0CE
tcolor: 6666CC

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Planet Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/rux-one
linkedin: https://linkedin.com/in/bart-karalus
twitter: https://twitter.com/binaryforgeltd
instagram: https://instagram.com/thehummingbeard
mastodon: https://fosstodon.org/@rux1


# Misc
nanobar: /js/nanobar.min.js
switch_light: 🔦
switch_dark: 🕶️

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: ruckus-one
